### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by ssbruno** [pivotal-cf/docs-pcf-dev#47]
Hi, I tried the steps mentioned in the link - https://docs.pivotal.io/pcf-dev/install-windows-legacy.html

When I tried to do **cf start dev**, I am gettting the below error.

Please sign in with your Pivotal Network account.
Need an account? Join Pivotal Network: https://network.pivotal.io

Email←[36;1m>←[0m xxx

Password←[36;1m>←[0m
←[31;1mFAILED←[0m
Error: Get https://network.pivotal.io/api/v2/api_token?password=xxx&username=xxx:
**x509: certificate signed by unknown authority.**

I am running the setup behind my company firewall. I have already set http_proxy.

Can you please assist?

**Comment by bentarnoff** [comment]
@ssisil Any thoughts on the above?

**Comment by animatedmax** [comment]
Hi @ssbruno Thank you for raising this issue, and we're sorry that you are having trouble.
Please sign in to [Pivotal Support](https://pivotal.io/support) and consult the community or open a case. See [Pivotal Support for Subscribers](https://content.pivotal.io/support/pivotal-support-for-subscribers) for how to do this.

If Pivotal Support's investigation determines that this is a general problem, rather than an issue that is fairly specific to your situation, we will update the documentation.
